name: Cypress Integration with CI
on:
  push:
    branches: main
jobs:
  Test-on-chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1,2]
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          command: "npm run cy:test"
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-video-chrome
          path: "${{github.workspace}}/cypress/videos"
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshot-chrome
          path: "${{github.workspace}}/cypress/screenshots"
