name: Cypress Integration with CI
on:
  push:
    branches: main
jobs:
  Test-on-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: cypress-io/github-action@v5.0.10
        with:
          runTests: false
      - name: Run tests
        uses: cypress-io/github-action@v5.0.10
        with:
          command: "npm run cy:test"
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-video-chrome
          path: "${{github.workspace}}/cypress/videos"
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshot-chrome
          path: "${{github.workspace}}/cypress/screenshots"
